name: Sync Fork

on:
  schedule:
    - cron: '*/1 * * * *' # Every minute
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Upstream Repository
        uses: actions/checkout@v3
        with:
          repository: devclub-nstru/server-admin-nxtup
          ref: main
          path: upstream-repo

      - name: Checkout Forked Repository
        uses: actions/checkout@v3
        with:
          repository: AdityaInnovates/server-admin-nxtup
          ref: main
          path: forked-repo

      - name: Check for Changes
        run: |
          cd upstream-repo
          git fetch origin
          UPSTREAM_HASH=$(git rev-parse HEAD)
          cd ../forked-repo
          git fetch origin
          FORK_HASH=$(git rev-parse origin/main)
          if [ "$UPSTREAM_HASH" = "$FORK_HASH" ]; then
            echo "No changes detected, fork is already synced."
            exit 0
          fi

      - name: Sync Changes
        run: |
          cd forked-repo
          git remote add upstream ../upstream-repo
          git fetch upstream
          git merge upstream/main
          git push origin main
